name: Keep Render awake

on: 
    schedule:
        - cron: "*/14 * * * *"
    workflow_dispatch:

jobs:
    ping:
        runs-on: ubuntu_latest
        steps:
            - name: Curl Render Health Endpoint
              run: curl -s https://ewallet-1-wrou.onrender.com/health


